package builtin


import "github.com/pingcap/parser/ast"

var datetimeFunctions = []*functionClass{
	{ast.AddDate, 3, 3, false, true},
	{ast.DateAdd, 3, 3, false, true},
	{ast.SubDate, 3, 3, false, true},
	{ast.DateSub, 3, 3, false, true},
	{ast.AddTime, 2, 2, false, true},
	{ast.ConvertTz, 3, 3, false, true},
	// {ast.Curdate, 0, 0, false, true},
	// {ast.CurrentDate, 0, 0, false, true},
	// {ast.CurrentTime, 0, 1, false, true},
	// {ast.CurrentTimestamp, 0, 1, false, true},
	// {ast.Curtime, 0, 1, false, true},
	{ast.Date, 1, 1, false, true},
	{ast.DateLiteral, 1, 1, false, true},
	{ast.DateFormat, 2, 2, false, true},
	{ast.DateDiff, 2, 2, false, true},
	{ast.Day, 1, 1, false, true},
	{ast.DayName, 1, 1, false, true},
	{ast.DayOfMonth, 1, 1, false, true},
	{ast.DayOfWeek, 1, 1, false, true},
	{ast.DayOfYear, 1, 1, false, true},
	{ast.Extract, 2, 2, false, true},
	{ast.FromDays, 1, 1, false, true},
	{ast.FromUnixTime, 1, 2, false, true},
	{ast.GetFormat, 2, 2, false, true},
	{ast.Hour, 1, 1, false, true},
	// {ast.LocalTime, 0, 1, false, true},
	// {ast.LocalTimestamp, 0, 1, true, true},
	{ast.MakeDate, 2, 2, false, true},
	{ast.MakeTime, 3, 3, false, true},
	{ast.MicroSecond, 1, 1, false, true},
	{ast.Minute, 1, 1, false, true},
	{ast.Month, 1, 1, false, true},
	{ast.MonthName, 1, 1, false, true},
	// {ast.Now, 0, 1, false, true},
	{ast.PeriodAdd, 2, 2, false, true},
	// {ast.PeriodDiff, 2, 2, false, true},
	{ast.Quarter, 1, 1, false, true},
	{ast.SecToTime, 1, 1, false, true},
	{ast.Second, 1, 1, false, true},
	{ast.StrToDate, 2, 2, false, true},
	{ast.SubTime, 2, 2, false, true},
	// will make diff
	// {ast.Sysdate, 0, 1, false, true},
	{ast.Time, 1, 1, false, true},
	{ast.TimeLiteral, 1, 1, false, true},
	{ast.TimeFormat, 2, 2, false, true},
	{ast.TimeToSec, 1, 1, false, true},
	{ast.TimeDiff, 2, 2, false, true},
	{ast.Timestamp, 1, 2, false, true},
	{ast.TimestampLiteral, 1, 2, false, true},
	{ast.TimestampAdd, 3, 3, false, true},
	{ast.TimestampDiff, 3, 3, false, true},
	{ast.ToDays, 1, 1, false, true},
	{ast.ToSeconds, 1, 1, false, true},
	// {ast.UnixTimestamp, 0, 1, false, true},
	// {ast.UTCDate, 0, 0, false, true},
	// {ast.UTCTime, 0, 1, false, true},
	// {ast.UTCTimestamp, 0, 1, false, true},
	{ast.Week, 1, 2, false, true},
	{ast.Weekday, 1, 1, false, true},
	{ast.WeekOfYear, 1, 1, false, true},
	{ast.Year, 1, 1, false, true},
	{ast.YearWeek, 1, 2, false, true},
	{ast.LastDay, 1, 1, false, true},
}
